// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZcqzcUWUoDXBXjxp-nVssbqR9dRb1AYI',
    appId: '1:904266210799:web:d57cc589e5714127652a1a',
    messagingSenderId: '904266210799',
    projectId: 'flutter-update-43996',
    authDomain: 'flutter-update-43996.firebaseapp.com',
    databaseURL: 'https://flutter-update-43996-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-43996.appspot.com',
    measurementId: 'G-YBXBV0LKKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQhI1k47oSv7zOQb0VwbVlaA7FSTWOlu0',
    appId: '1:904266210799:android:8b8220818d2162d0652a1a',
    messagingSenderId: '904266210799',
    projectId: 'flutter-update-43996',
    databaseURL: 'https://flutter-update-43996-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-43996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_dHdC5a1ZrQ7OgMejqeeATNgUwQqPoI',
    appId: '1:904266210799:ios:8bdb45baa83d194d652a1a',
    messagingSenderId: '904266210799',
    projectId: 'flutter-update-43996',
    databaseURL: 'https://flutter-update-43996-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-43996.appspot.com',
    iosClientId: '904266210799-cfuq2rqugitvfhvr2q6d8lsud5ou9kre.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_dHdC5a1ZrQ7OgMejqeeATNgUwQqPoI',
    appId: '1:904266210799:ios:8bdb45baa83d194d652a1a',
    messagingSenderId: '904266210799',
    projectId: 'flutter-update-43996',
    databaseURL: 'https://flutter-update-43996-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-43996.appspot.com',
    iosClientId: '904266210799-cfuq2rqugitvfhvr2q6d8lsud5ou9kre.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShop',
  );
}
